typography_spectrum: 0.10222
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.843431374290958
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.93217
analytics:
  google: null
  facebook: null
  twitter: null
name: Oprust Photography
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Ole Petter Rust
purpose: []
