name: Ole Petter Rust Photography
favicon: null
layout_spectrum: 0.9531947621144354
typography_spectrum: 0.5750917023979127
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8579517747275531
  lightness: 0.31027804175391793
  saturation: 0.843431374290958
  rhythmicContrast: 0.07496223645284772
purpose: []
